version: 2
updates:
- package-ecosystem: npm
  directory: "/functions"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/i18n"
    versions:
    - 0.12.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: chalk
    versions:
    - 4.1.0
